pipeline:
  test:
    image: python:3.5.2
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.dev
    commands:
      - pip install tox
      - make env
      - make dev
      - make flake8
      - tox

  docker:
    image: plugins/docker
    repo: registry.fap.no/p0sx/p0sx
    insecure: true
    tags:
        - master
    when:
        branch: master

  docker:
    image: plugins/docker
    repo: registry.fap.no/p0sx/p0sx
    insecure: true
    tags:
        - latest
        - $$TAG
    when:
        event: tag

  ssh:
    image: appleboy/drone-ssh
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    command_timeout: 1000
    script:
      - docker pull registry.fap.no/p0sx/p0sx:latest
      - docker-compose -f /srv/docker/p0sx/docker-compose.yml down p0sx-dev
      - docker-compose -f /srv/docker/p0sx/docker-compose.yml up -d p0sx-dev
    when:
        status: success
        branch: master

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ pkumar2@spscommerce.com, test@example.com  ]
    when:
      status: [ success, changed, failure ]
